import { NextResponse } from "next/server";
import { getServiceClient } from "@/lib/supabase";
import { getOrgBySlug } from "@/lib/db-queries";

/**
 * Retry/regenerate feedback on a generated image.
 * Deletes the cached generated image row so the next generation is fresh.
 */
export async function POST(request: Request) {
  try {
    const { generatedImageId, sessionId, orgSlug } = await request.json();

    if (!generatedImageId || !sessionId || !orgSlug) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const supabase = getServiceClient();

    // Validate org
    const org = await getOrgBySlug(orgSlug);
    if (!org) return NextResponse.json({ error: "Not found" }, { status: 404 });

    // Validate session belongs to org
    const { data: session } = await supabase
      .from("buyer_sessions")
      .select("id, org_id")
      .eq("id", sessionId)
      .single();

    if (!session || session.org_id !== org.id) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }

    // Validate generated image exists, belongs to this org, and was generated by this session
    const { data: image } = await supabase
      .from("generated_images")
      .select("id")
      .eq("id", generatedImageId)
      .eq("org_id", org.id)
      .eq("buyer_session_id", sessionId)
      .single();

    if (!image) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }

    // Delete the cached image row so regeneration produces a fresh result
    await supabase
      .from("generated_images")
      .delete()
      .eq("id", generatedImageId);

    return NextResponse.json({ ok: true });
  } catch (error) {
    console.error("[generate/photo/feedback] Error:", error);
    return NextResponse.json({ error: "Failed to process feedback" }, { status: 500 });
  }
}
