#!/usr/bin/env npx tsx
/**
 * Test 2: Texture composite approach for backsplash.
 * 1. Extract backsplash mask (reuse from masked test)
 * 2. Tile the swatch texture across the masked area
 * 3. Composite tiled texture onto the original photo
 * 4. Send the composite to OpenAI for lighting/blending refinement
 *
 * Usage: npx tsx scripts/test-backsplash-composite.ts
 */

import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(__dirname, "..", ".env.local") });

import OpenAI, { toFile } from "openai";
import { GoogleGenAI } from "@google/genai";
import { createClient } from "@supabase/supabase-js";
import sharp from "sharp";
import fs from "fs";

function getEnvOrDie(key: string): string {
  const val = process.env[key];
  if (!val) { console.error(`Missing env var: ${key}`); process.exit(1); }
  return val;
}

const supabase = createClient(getEnvOrDie("NEXT_PUBLIC_SUPABASE_URL"), getEnvOrDie("SUPABASE_SERVICE_ROLE_KEY"));
const openai = new OpenAI();
const ai = new GoogleGenAI({ apiKey: getEnvOrDie("GOOGLE_GENERATIVE_AI_API_KEY") });

const OUTPUT_DIR = path.join(__dirname, "backsplash-test-outputs", "texture-composite");
fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const KITCHEN_PHOTO = "364538bf-1712-48e7-a905-04ad90983eb2/rooms/d3b60a74-1ee6-4dd1-a313-99d636f5a7b2/kitchen-close.webp";

// ---------------------------------------------------------------------------
// Step 1: Generate backsplash mask (same as masked test, with caching)
// ---------------------------------------------------------------------------
async function generateBacksplashMask(roomBuffer: Buffer): Promise<Buffer> {
  // Check if mask was already generated by the masked inpaint test
  const sharedMask = path.join(__dirname, "backsplash-test-outputs", "masked-inpaint", "backsplash-mask.png");
  const localMask = path.join(OUTPUT_DIR, "backsplash-mask.png");

  if (fs.existsSync(localMask)) {
    console.log("  Using cached mask");
    return fs.readFileSync(localMask);
  }
  if (fs.existsSync(sharedMask)) {
    console.log("  Using mask from masked-inpaint test");
    fs.copyFileSync(sharedMask, localMask);
    return fs.readFileSync(localMask);
  }

  console.log("  Generating backsplash mask with Gemini...");
  const base64Image = roomBuffer.toString("base64");
  const { width, height } = await sharp(roomBuffer).metadata();

  const response = await ai.models.generateContent({
    model: "gemini-3-pro-image-preview",
    contents: [{
      role: "user",
      parts: [
        { inlineData: { mimeType: "image/webp", data: base64Image } },
        { text: `Generate a segmentation mask for the BACKSPLASH ONLY in this kitchen photo.

Output a ${width}x${height} image where:
- BACKSPLASH area = pure WHITE (#FFFFFF)
- EVERYTHING else = pure BLACK (#000000)

Only the tile surface between upper cabinets and countertop. Crisp edges. No appliances, outlets, or non-backsplash surfaces. Pure black and white.` },
      ],
    }],
    config: { responseModalities: ["image", "text"] },
  });

  const parts = response.candidates?.[0]?.content?.parts ?? [];
  for (const part of parts) {
    if (part.inlineData?.data) {
      const maskBuffer = Buffer.from(part.inlineData.data, "base64");
      const processed = await sharp(maskBuffer)
        .resize(width!, height!)
        .grayscale()
        .threshold(128)
        .png()
        .toBuffer();
      fs.writeFileSync(localMask, processed);
      return processed;
    }
  }
  throw new Error("Gemini did not return a mask image");
}

// ---------------------------------------------------------------------------
// Step 2: Tile the swatch texture and composite onto the room photo
// ---------------------------------------------------------------------------
async function compositeTexture(
  roomBuffer: Buffer,
  swatchBuffer: Buffer,
  maskBuffer: Buffer,
): Promise<Buffer> {
  const { width: roomW, height: roomH } = await sharp(roomBuffer).metadata();

  // Create a tiled texture that covers the full image dimensions
  const swatchMeta = await sharp(swatchBuffer).metadata();
  const tileW = swatchMeta.width!;
  const tileH = swatchMeta.height!;

  // Calculate how many tiles we need
  const cols = Math.ceil(roomW! / tileW) + 1;
  const rows = Math.ceil(roomH! / tileH) + 1;

  // Create tiled texture using sharp composite
  const tiledWidth = cols * tileW;
  const tiledHeight = rows * tileH;

  // Build tile grid
  const tileComposites: sharp.OverlayOptions[] = [];
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      tileComposites.push({
        input: swatchBuffer,
        left: c * tileW,
        top: r * tileH,
      });
    }
  }

  const tiledTexture = await sharp({
    create: { width: tiledWidth, height: tiledHeight, channels: 3, background: { r: 128, g: 128, b: 128 } }
  })
    .composite(tileComposites)
    .resize(roomW!, roomH!, { fit: "cover" })
    .png()
    .toBuffer();

  fs.writeFileSync(path.join(OUTPUT_DIR, "01_tiled_texture.png"), tiledTexture);

  // Now composite: where mask is white, use tiled texture; where black, use original room
  const roomRgba = await sharp(roomBuffer).resize(roomW!, roomH!).ensureAlpha().raw().toBuffer();
  const textureRgba = await sharp(tiledTexture).ensureAlpha().raw().toBuffer();
  const maskGray = await sharp(maskBuffer).resize(roomW!, roomH!).grayscale().raw().toBuffer();

  const result = Buffer.from(roomRgba);
  for (let i = 0; i < maskGray.length; i++) {
    if (maskGray[i] > 128) {
      result[i * 4] = textureRgba[i * 4];
      result[i * 4 + 1] = textureRgba[i * 4 + 1];
      result[i * 4 + 2] = textureRgba[i * 4 + 2];
    }
  }

  return sharp(result, { raw: { width: roomW!, height: roomH!, channels: 4 } })
    .png()
    .toBuffer();
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  console.log("=== Texture Composite: Backsplash ===\n");

  // Download room photo
  console.log("Downloading room photo...");
  const { data: imageData, error } = await supabase.storage.from("rooms").download(KITCHEN_PHOTO);
  if (error || !imageData) throw new Error(`Failed: ${error?.message}`);
  const roomBuffer = Buffer.from(await imageData.arrayBuffer());
  fs.writeFileSync(path.join(OUTPUT_DIR, "00_source.png"), roomBuffer);

  // Download HQ swatch
  const { data: swatchData } = await supabase.storage.from("swatches").download(
    "364538bf-1712-48e7-a905-04ad90983eb2/backsplash/baker-blvd-picket-gloss-taupe-hq.jpg"
  );
  if (!swatchData) throw new Error("Failed to download swatch");
  const swatchBuffer = Buffer.from(await swatchData.arrayBuffer());

  // Step 1: Generate mask
  console.log("\nStep 1: Backsplash mask");
  const maskBuffer = await generateBacksplashMask(roomBuffer);

  // Step 2: Tile texture onto backsplash area
  console.log("\nStep 2: Compositing tiled texture");
  const compositeBuffer = await compositeTexture(roomBuffer, swatchBuffer, maskBuffer);
  fs.writeFileSync(path.join(OUTPUT_DIR, "02_raw_composite.png"), compositeBuffer);
  console.log("  Saved raw composite (no lighting fix yet)");

  // Step 3: Send composite to OpenAI for lighting/blending refinement
  console.log("\nStep 3: AI lighting/blending pass");
  const inputImages = [
    await toFile(compositeBuffer, "composite.png", { type: "image/png" }),
  ];

  const prompt = `This kitchen photo has a new backsplash tile texture composited in, but it looks flat and unnatural because it has no perspective, lighting, or shadow adjustments.

Refine ONLY the backsplash area to look naturally installed:
- Add realistic lighting and shadows that match the rest of the kitchen
- Apply subtle perspective correction so tiles recede naturally toward the back wall
- Add grout line shadows and tile depth/reflection consistent with the glossy finish
- Blend the edges where backsplash meets cabinets and countertop

PRESERVE:
- Keep the exact tile pattern, shape, and color — do NOT change the tile design
- Keep everything outside the backsplash completely unchanged
- Keep the exact camera angle, perspective, and room layout
- Photorealistic result`;

  fs.writeFileSync(path.join(OUTPUT_DIR, "prompt_composite.txt"), prompt);

  const genStart = performance.now();
  const result = await openai.images.edit({
    model: "gpt-image-1.5",
    image: inputImages,
    prompt,
    quality: "medium",
    size: "1536x1024",
    input_fidelity: "high",
  });

  const durationMs = Math.round(performance.now() - genStart);
  const img = result.data?.[0];
  if (!img?.b64_json) throw new Error("No image generated");

  const outputPath = path.join(OUTPUT_DIR, "03_refined_composite.png");
  fs.writeFileSync(outputPath, Buffer.from(img.b64_json, "base64"));
  console.log(`  Done in ${(durationMs / 1000).toFixed(1)}s → ${outputPath}`);

  console.log(`\nOutputs in ${OUTPUT_DIR}/:`);
  console.log("  00_source.png — original kitchen");
  console.log("  01_tiled_texture.png — flat tiled swatch");
  console.log("  02_raw_composite.png — texture pasted onto backsplash (no lighting)");
  console.log("  03_refined_composite.png — AI-refined with lighting/shadows");
}

main().catch(err => { console.error("Fatal:", err); process.exit(1); });
